services:
  expense-dashboard:
    build:
      context: .
      args:
        DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public&connect_timeout=60
    restart: unless-stopped
    container_name: expense-dashboard
    networks:
      condominium-network:
        ipv4_address: 172.18.55.11
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/app
      - /app/node_modules

networks:
  condominium-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.55.0/16
