openapi: 3.0.0
info:
  title: Documentação
  version: "1.0"
paths:
  /api/expenses:
    $ref: ./routes/expenses/common.yaml
  /api/expenses/{id}:
    $ref: ./routes/expenses/expense.yaml
  /api/residents:
    $ref: ./routes/residents/common.yaml
  /api/residents{id}:
    $ref: ./routes/residents/resident.yaml
